#docker build -t physalia_buoy .

#docker run -d --privileged --rm --name buoy -p 1234:80 -v /dev:/dev physalia_buoy

#docker run -it --privileged --rm  -p 1234:80 -v /dev:/dev physalia_buoy /sbin/init
#-------------------------------------------------------------------------------------
FROM debian:latest
LABEL "GNU Affero General Public License v3 (AGPL-3.0)"="julien.ancelin@inrae.fr"

RUN apt-get update && apt-get install -y wget git apt-utils systemd lsb-release

RUN wget https://raw.githubusercontent.com/jancelin/rtkbase/dev_rtkrover/tools/install.sh
RUN find ./ -type f -iname "*.sh" -exec chmod +x {} \;
RUN sed -i -e "s/\$(logname)/root/g" ./install.sh
RUN sed -i -e "s/sudo -u root//g" ./install.sh
RUN ./install.sh --dependencies --rtklib --rtkbase-repo --gpsd-chrony 
RUN sed -i -e "s/\$(logname)/root/g" ./rtkbase/copy_unit.sh
RUN ./install.sh --unit-files

CMD [ "/sbin/init" ]
