{
 "title": "Bouee GNSS LIENSS/INRAE",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Elevation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "meters" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  height,\n  buoy_name\nFROM llh_buoy\nWHERE\n  $__timeFilter(dat)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "height max - height min Meters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n -- dat AS \"time\",\n  max(height)-min(height) as dif,\n  buoy_name as buoy_name\nFROM llh_buoy\nWHERE\n  $__timeFilter(dat)\nGROUP BY buoy_name\n--ORDER BY 1"
    }
   ]
  },
  {
   "title": "Qualité",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  q,\n  buoy_name\nFROM llh_buoy\nWHERE\n  $__timeFilter(dat)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  ratio,\n  buoy_name\nFROM llh_buoy\nWHERE\n  $__timeFilter(dat)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  age,\n  buoy_name\nFROM llh_buoy\nWHERE\n  $__timeFilter(dat)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Sat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  ns,\n  buoy_name\nFROM llh_buoy\nWHERE\n  $__timeFilter(dat)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Qualité",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "1 fix / 2 float / 5 single" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  q,\n  buoy_name\nFROM llh_buoy\nWHERE\n  $__timeFilter(dat)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SDU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  sdu,\n  buoy_name\nFROM llh_buoy\nWHERE\n  $__timeFilter(dat)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 10 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  lati,\n  longi,\n  buoy_name\nFROM llh_buoy\nWHERE\n  $__timeFilter(dat)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  ratio,\n  buoy_name\nFROM llh_buoy\nWHERE\n  $__timeFilter(dat)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SDN",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  sdn,\n  buoy_name\nFROM llh_buoy\nWHERE\n  $__timeFilter(dat)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Nombre de satellites",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  ns,\n  buoy_name\nFROM llh_buoy\nWHERE\n  $__timeFilter(dat)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SDE",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  sde,\n  buoy_name\nFROM llh_buoy\nWHERE\n  $__timeFilter(dat)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "table",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  id,\n  dat,\n  lati,\n  longi,\n  height,\n  q,\n  ns,\n  sdn,\n  sde,\n  sdu,\n  sdne,\n  sdeu,\n  sdun,\n  age,\n  ratio,\n  buoy_name AS \"buoy\"\nFROM llh_buoy\nWHERE\n  $__timeFilter(dat)\nORDER BY 1"
    }
   ]
  }
 ]
}